import UVRR
#print axioms CastingVote.noninterference
#print axioms CastingVote.guard_preserved
#print axioms CastingVote.completes_phase1
#print axioms CastingVote.example3
#print axioms Counterexample.intra_ok
#print axioms Counterexample.cross_fails
#print axioms Counterexample.not_p1
#print axioms Counterexample.eraMono
#print axioms Counterexample.eraLe
#print axioms Counterexample.p23
#print axioms Counterexample.p4
#print axioms Counterexample.p5
#print axioms Counterexample.p6
#print axioms Counterexample.p7
#print axioms Counterexample.two_chosen
#print axioms Counterexample.cross_frown_necessary
#print axioms Frown.symm
#print axioms Paxos.lemma9
#print axioms Paxos.toSynod_inv
#print axioms Paxos.theorem10
#print axioms bLt_iff
#print axioms bLt_wf
#print axioms bLt_trans
#print axioms bLt_irrefl
#print axioms bLt_total
#print axioms bLt_era_mono
#print axioms Paxos.theorem10_lex
#print axioms Paxos.eraMono_lex
#print axioms frownB_iff
#print axioms p1B_sound
#print axioms hotswap_ge2
#print axioms hotswap_p1
#print axioms wholesale_intra
#print axioms wholesale_cross_fails
#print axioms Synod.lemma6
#print axioms Synod.lemma7
#print axioms Synod.theorem8
#print axioms rows_ok
#print axioms rows_p1
#print axioms plus_two_breaks
