// agent366 citation graph data — categories invented; edges verified against
// local corpus texts (research/agent366/md, papers/turner-paxos-reconf.tex)
// or the works' own abstracts. No spurious associations: each edge is backed
// by a citation observed in the source text.
// Nodes carry tags (topic keywords) and seeAlso (substitutes / closest
// relatives — works one could cite or read INSTEAD of or ALONGSIDE this one).
const CATEGORIES = {
  consensusClassic: { name: "Paxos/VR classics", color: "#5470c6" },
  reconfiguration: { name: "Reconfiguration", color: "#91cc75" },
  raftLine: { name: "Raft (Ousterhout/Ongaro)", color: "#fac858" },
  ramcloud: { name: "RAMCloud storage", color: "#ee6666" },
  homa: { name: "Homa transport", color: "#73c0de" },
  durability: { name: "Crash consistency / durability", color: "#fc8452" },
  metadata: { name: "Metadata services", color: "#9a60b4" },
  uvrr: { name: "uVRR (this repo)", color: "#ea7ccc" },
  selfBlog: { name: "Self-published blog", color: "#bbbbbb" }
};

const NODES = [
  { id: "vr1988", name: "Viewstamped Replication (PODC '88)", cat: "consensusClassic",
    authors: "Oki & Liskov", venue: "ACM PODC 1988",
    url: "https://www.cs.princeton.edu/courses/archive/fall11/cos518/papers/viewstamped.pdf",
    abstract: "One of the potential benefits of distributed systems is their use to provide highly-available services. We describe a primary copy method for managing replicated data that supports highly-available distributed systems. The method provides consistency even in the face of node failures and restarts.", tags: ["consensus", "primary-backup", "crash-recovery"], seeAlso: ["vrr2012", "pms2001"] },
  { id: "vrr2012", name: "Viewstamped Replication Revisited", cat: "consensusClassic",
    authors: "Liskov & Cowling", venue: "MIT-CSAIL-TR-2012-021",
    url: "https://hdl.handle.net/1721.1/71763",
    abstract: "This paper presents an updated version of Viewstamped Replication, a replication technique that handles failures in which nodes crash. It describes how client requests are handled, how the group reorganizes when a replica fails, and how a failed replica is able to rejoin the group. The paper also describes a number of important optimizations and presents a protocol for handling reconfigurations that can change both the group membership and the number of failures the group is able to handle.", tags: ["consensus", "diskless-normal-path", "rejoin", "reconfiguration"], seeAlso: ["vr1988", "raft2014", "diskless", "uvrrpaper"] },
  { id: "pms2001", name: "Paxos Made Simple", cat: "consensusClassic",
    authors: "Lamport", venue: "SIGACT News 2001",
    url: "https://lamport.azurewebsites.net/pubs/paxos-simple.pdf",
    abstract: "The Paxos algorithm, when presented in plain English, is very simple.", tags: ["consensus", "paxos", "majority-quorums"], seeAlso: ["diskpaxos", "verticalpaxos", "raft2014"] },
  { id: "diskpaxos", name: "Disk Paxos", cat: "consensusClassic",
    authors: "Gafni & Lamport", venue: "Distributed Computing 2003",
    url: "https://lamport.azurewebsites.net/pubs/disk-paxos-disc.pdf",
    abstract: "A method is described for implementing a distributed shared register with processor consensus using disks; it substitutes reliable disk writes for reliable processor-to-processor communication.", tags: ["consensus", "shared-disks", "replicated-registers"], seeAlso: ["pms2001"] },
  { id: "verticalpaxos", name: "Vertical Paxos (PODC '09)", cat: "consensusClassic",
    authors: "Lamport, Malkhi, Zhou", venue: "PODC 2009",
    url: "https://lamport.azurewebsites.net/pubs/vertical-paxos.pdf",
    abstract: "We introduce a class of Paxos algorithms called Vertical Paxos, in which reconfiguration can occur in the middle of reaching agreement on an individual state-machine command. Vertical Paxos algorithms use an auxiliary configuration master that facilitates agreement on reconfiguration. A special case of these algorithms leads to traditional primary-backup protocols.", tags: ["consensus", "reconfiguration", "auxiliary-master", "primary-backup"], seeAlso: ["reconfigsm", "disc2017", "turner"] },
  { id: "disc2017", name: "Vertical Paxos & Primary-Backup (DISC '17)", cat: "consensusClassic",
    authors: "Michael, Spiegelman, Andersen, Lloyd", venue: "DISC 2017",
    url: "https://arxiv.org/abs/1708.04871",
    abstract: "We present Vertical Paxos, a family of Paxos algorithms in which reconfiguration may occur in the middle of agreement on an individual command, and identify the published recovery protocol's amnesia failure.", tags: ["consensus", "reconfiguration", "primary-backup", "amnesia-failure"], seeAlso: ["verticalpaxos", "diskless"] },
  { id: "reconfigsm", name: "Reconfiguring a State Machine", cat: "reconfiguration",
    authors: "Lamport, Malkhi, Zhou", venue: "SIGACT News 2010",
    url: "http://www-sop.inria.fr/members/Francesco.Bongiovanni/reconfiguring%20a%20state%20machine.pdf",
    abstract: "A tutorial on reconfiguration in replicated state machines, covering window-based reconfiguration and the history of the problem.", tags: ["reconfiguration", "tutorial", "window-property"], seeAlso: ["verticalpaxos", "fqi2016", "turner"] },
  { id: "fqi2016", name: "Flexible Quorum Intersection Revisited", cat: "reconfiguration",
    authors: "Howard, Malkhi, Spiegelman", venue: "arXiv 2016",
    url: "https://arxiv.org/pdf/1608.06696",
    abstract: "Flexible Paxos showed that Paxos' quorum requirements were over-specified: the phase-I and phase-II quorums need not both be majorities, as long as they intersect.", tags: ["reconfiguration", "quorum-relaxation", "flexible-paxos"], seeAlso: ["pms2001", "turner", "reconfigsm"] },
  { id: "turner", name: "UPaxos: Unbounded Pipelining in Dynamically Reconfigurable Paxos Clusters", cat: "reconfiguration",
    authors: "David Turner", venue: "Tracsis tech report, rev 1A9DBA37",
    url: "https://github.com/DaveCTurner/paxos-membership",
    abstract: "Paxos clusters whose membership changes dynamically through voting weights, era-indexed configurations, leader overlap and the casting vote; safety proofs formalised in Isabelle/HOL. Notes that quorum-intersection relaxations were discovered independently by Howard, Malkhi and Spiegelman.", tags: ["reconfiguration", "voting-weights", "casting-vote", "unbounded-pipelining", "isabelle"], seeAlso: ["fqi2016", "verticalpaxos", "vrr2012", "uvrrpaper"] },
  { id: "raft2014", name: "Raft: In Search of an Understandable Consensus Algorithm", cat: "raftLine",
    authors: "Ongaro & Ousterhout", venue: "USENIX ATC 2014 (Best Paper)",
    url: "https://www.usenix.org/system/files/conference/atc14/atc14-paper-ongaro.pdf",
    abstract: "Raft is a consensus algorithm for managing a replicated log. It produces a result equivalent to (multi-)Paxos, and it is as efficient as Paxos, but its structure is different from Paxos; this makes Raft more understandable than Paxos and also provides a better foundation for building practical systems. Raft also includes a new mechanism for changing the cluster membership, which uses overlapping majorities to guarantee safety.", tags: ["consensus", "leader-election", "understandability", "joint-consensus"], seeAlso: ["ongarodiss", "pms2001", "vrr2012", "epaxosrev"] },
  { id: "ongarodiss", name: "Consensus: Bridging Theory and Practice (PhD)", cat: "raftLine",
    authors: "Diego Ongaro (advisor: Ousterhout)", venue: "Stanford PhD 2014",
    url: "https://purl.stanford.edu/qr033xr6097",
    abstract: "This dissertation presents a new consensus algorithm called Raft, which was designed for understandability. Raft first elects a server as leader, then concentrates all decision-making onto the leader... To change the cluster membership, Raft allows adding or removing one server at a time, and the cluster continues servicing requests throughout the change.", tags: ["consensus", "leadership", "membership-change", "log-compaction"], seeAlso: ["raft2014", "logcabin"] },
  { id: "logcabin", name: "LogCabin", cat: "raftLine",
    authors: "Diego Ongaro", venue: "system, github.com/logcabin/logcabin",
    url: "https://github.com/logcabin/logcabin",
    abstract: "A coordination service (distributed key-value store) built on the Raft consensus algorithm; Ongaro's post-dissertation implementation vehicle.", tags: ["coordination-service", "raft-implementation"], seeAlso: ["raft2014", "zookeeper"] },
  { id: "epaxosrev", name: "EPaxos Revisited", cat: "raftLine",
    authors: "Tollman, Park, Ousterhout", venue: "NSDI 2021",
    url: "https://www.usenix.org/conference/nsdi21/presentation/tollman",
    abstract: "This paper re-evaluates the performance of the EPaxos consensus protocol for geo-replication... Our re-evaluation confirms the original claim that EPaxos provides optimal median commit latency in a WAN, but it shows much worse tail latency than previously reported (more than 4x worse than Multi-Paxos).", tags: ["consensus", "geo-replication", "tail-latency", "clocks"], seeAlso: ["raft2014", "pms2001"] },
  { id: "curp", name: "CURP: Exploiting Commutativity for Practical Fast Replication", cat: "raftLine",
    authors: "Park & Ousterhout", venue: "NSDI 2019",
    url: "https://www.usenix.org/conference/nsdi19/presentation/park",
    abstract: "We show that this entanglement of ordering and durability is unnecessary for strong consistency. Consistent Unordered Replication Protocol (CURP) allows clients to replicate requests that have not yet been ordered, as long as they are commutative. This strategy allows most operations to complete in 1 RTT. In RAMCloud, CURP improved write latency by ~2x (14us -> 7.1us).", tags: ["replication", "1-RTT", "commutativity", "durability-decoupled"], seeAlso: ["ramcloud", "raft2014", "vrr2012", "uvrrpaper"] },
  { id: "caseforramcloud", name: "The Case for RAMClouds", cat: "ramcloud",
    authors: "Ousterhout et al.", venue: "SIGOPS OSR 2009 / CACM 2011",
    url: "https://web.stanford.edu/~ouster/cgi-bin/papers/ramcloud.pdf",
    abstract: "This paper argues for a new approach to datacenter storage called RAMCloud, where information is kept entirely in DRAM and large-scale systems are created by aggregating the main memories of thousands of commodity servers. RAMClouds can provide durable and available storage with 100-1000x the throughput of disk-based systems and 100-1000x lower access latency.", tags: ["storage", "DRAM", "low-latency", "position-paper"], seeAlso: ["ramcloud", "blogNetdisk"] },
  { id: "ramcloud", name: "The RAMCloud Storage System", cat: "ramcloud",
    authors: "Ousterhout et al. (incl. Ongaro)", venue: "ACM TOCS 33(3) 2015",
    url: "https://web.stanford.edu/~ouster/cgi-bin/papers/ramcloud-tocs.pdf",
    abstract: "RAMCloud is a storage system that provides low-latency access to large-scale datasets. To achieve low latency, RAMCloud stores all data in DRAM at all times... RAMCloud ensures the durability of DRAM-based data by keeping backup copies on secondary storage... client applications can read small objects from any RAMCloud storage server in less than 5µs, durable writes of small objects take about 13.5µs.", tags: ["storage", "DRAM", "log-structured", "fast-recovery"], seeAlso: ["caseforramcloud", "homa2018", "curp"] },
  { id: "homa2018", name: "Homa: A Receiver-Driven Low-Latency Transport Protocol", cat: "homa",
    authors: "Montazeri, Li, Alizadeh, Ousterhout", venue: "SIGCOMM 2018",
    url: "https://people.csail.mit.edu/alizadeh/papers/homa-sigcomm18.pdf",
    abstract: "Homa is a new transport protocol for datacenter networks. It provides exceptionally low latency, especially for workloads with a high volume of very short messages, and it also supports large messages and high network utilization. Homa uses in-network priority queues to ensure low latency for short messages; priority allocation is managed dynamically by each receiver and integrated with a receiver-driven flow control mechanism. Our implementation delivers 99th percentile round-trip times less than 15 µs for short messages on a 10 Gbps network running at 80% load.", tags: ["transport", "receiver-driven", "SRPT", "priority-queues"], seeAlso: ["homalinux", "replacetcp", "ramcloud"] },
  { id: "homalinux", name: "A Linux Kernel Implementation of Homa", cat: "homa",
    authors: "John Ousterhout", venue: "USENIX ATC 2021",
    url: "https://www.usenix.org/conference/atc21/presentation/ousterhout",
    abstract: "Homa/Linux is a Linux kernel module that implements the Homa transport protocol. In a cluster benchmark with 40 nodes, Homa/Linux provided lower latency than both TCP and DCTCP for all message sizes; for short messages, Homa's 99th percentile tail latency was 7–83x lower than TCP and DCTCP. The benchmarks also show that Homa has eliminated network congestion as a significant performance limitation.", tags: ["transport", "kernel-module", "tail-latency"], seeAlso: ["homa2018", "replacetcp"] },
  { id: "replacetcp", name: "It's Time to Replace TCP in the Datacenter", cat: "homa",
    authors: "John Ousterhout", venue: "arXiv 2210.00714 (2022); CACM 66(4) 2023",
    url: "https://arxiv.org/abs/2210.00714",
    abstract: "Every significant element of TCP, from its stream orientation to its expectation of in-order packet delivery, is wrong for the datacenter. It is time to recognize that TCP's problems are too fundamental and interrelated to be fixed; the only way to harness the full performance potential of modern networks is to introduce a new transport protocol into the datacenter. Homa demonstrates that it is possible to create a transport protocol that avoids all of TCP's problems.", tags: ["transport", "position-paper", "TCP-replacement"], seeAlso: ["homa2018", "homalinux", "omatalk"] },
  { id: "omatalk", name: "Homa: The End of TCP for AI Clusters (talk)", cat: "homa",
    authors: "John Ousterhout", venue: "AI Engineer, 2026-09-17",
    url: "https://www.youtube.com/watch?v=eZ8WWZzoaR0",
    abstract: "Talk: AI workloads are shifting from large throughput-dominated transfers to smaller latency-critical ones; TCP and RDMA both mishandle that shift. Homa is message-based, receiver-driven, and uses switch priority queues to approximate SRPT; tail latency for short messages is >10x better than TCP. Needs only the priority queues already present in modern commodity switches. Ends with an open invitation to collaborate.", tags: ["transport", "AI-clusters", "talk"], seeAlso: ["replacetcp", "homa2018"] },
  { id: "lampson", name: "Crash Recovery in a Distributed Data Storage System", cat: "durability",
    authors: "Lampson & Sturgis", venue: "Xerox PARC 1979",
    url: "https://www.microsoft.com/en-us/research/wp-content/uploads/1979/01/21.-Lampson-and-Sturgis-Crash-recovery-in-a-distributed-data-storage-system.pdf",
    abstract: "An algorithm is described which guarantees reliable storage of data in a distributed system, even when different portions of the data base, stored on separate machines, are updated as part of a single transaction.", tags: ["durability", "transactions", "stable-storage", "two-phase-commit"], seeAlso: ["vrr2012", "allfs"] },
  { id: "allfs", name: "All File Systems Are Not Created Equal (OSDI '14)", cat: "durability",
    authors: "Pillai, Chidambaram, Alagappan, Arpaci-Dusseau, Arpaci-Dusseau", venue: "OSDI 2014",
    url: "https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-pillai.pdf",
    abstract: "File systems have evolved through a crash-consistency contract... applications must carefully order writes and use fsync correctly, or risk corruption; we analyze how ten widely-used applications craft crash-consistent updates and how file systems make this complex.", tags: ["crash-consistency", "fsync", "file-systems"], seeAlso: ["optfs", "lampson"] },
  { id: "optfs", name: "Optimistic Crash Consistency (SOSP '13)", cat: "durability",
    authors: "Chidambaram, Pillai, Arpaci-Dusseau, Arpaci-Dusseau", venue: "SOSP 2013",
    url: "https://research.cs.wisc.edu/adsl/Publications/optfs-sosp13.pdf",
    abstract: "We introduce optimistic crash consistency, a new approach to crash consistency in journaling file systems, exploiting the cache flush and barrier mechanisms to obtain better performance while remaining crash consistent.", tags: ["crash-consistency", "journaling", "optimistic"], seeAlso: ["allfs", "diskless"] },
  { id: "diskless", name: "Providing Stable Storage for the Diskless Crash-Recovery Failure Model", cat: "durability",
    authors: "Michael, Ports, Sharma, Szekeres", venue: "UW-CSE-16-08-02",
    url: "https://syslab.cs.washington.edu/papers/diskless-tr16.pdf",
    abstract: "We study the diskless crash-recovery failure model in which only volatile memory is assumed... and show the published VR recovery protocol's amnesia failure and its fix.", tags: ["crash-recovery", "failure-model", "amnesia", "VR"], seeAlso: ["vrr2012", "par", "disc2017"] },
  { id: "par", name: "Protocol-Aware Recovery for Consensus-Based Storage (FAST '18)", cat: "durability",
    authors: "Alagappan, Ganesan, Lee, Albarghouthi, Chidambaram, Arpaci-Dusseau, Arpaci-Dusseau", venue: "USENIX FAST 2018 (Best Paper)",
    url: "https://www.usenix.org/system/files/conference/fast18/fast18-alagappan.pdf",
    abstract: "A single disk sector fault, in the write-ahead log of a single replica, can propagate through the distributed Raft or MultiPaxos consensus protocol, to cause global cluster data loss; recovery must be protocol-aware.", tags: ["recovery", "bitrot", "protocol-aware", "WAL"], seeAlso: ["diskless", "raft2014", "zookeeper", "tigerbeetle"] },
  { id: "zookeeper", name: "ZooKeeper: Wait-free coordination (ATC '10)", cat: "metadata",
    authors: "Hunt, Konar, Junqueira, Reed", venue: "USENIX ATC 2010",
    url: "https://www.usenix.org/events/usenix10/tech/full_papers/Hunt.pdf",
    abstract: "Coordinating distributed applications requires services providing distributed process coordination primitives. We describe the design, implementation, and evaluation of ZooKeeper, a service providing wait-free coordination, built on a primary-backup variant of Paxos (Zab).", tags: ["coordination-service", "zab", "primary-backup"], seeAlso: ["logcabin", "corfu", "raft2014"] },
  { id: "corfu", name: "CORFU: A Distributed Shared Log (TOCS 2013)", cat: "metadata",
    authors: "Balakrishnan, Malkhi, Davis, Prabhakaran, Wei, Wobber", venue: "ACM TOCS 31(4) 2013",
    url: "https://doi.org/10.1145/2535930",
    abstract: "CORFU is a global log which clients can append-to and read-from over a network. Internally, CORFU is distributed over a cluster of machines in such a way that there is no single I/O bottleneck to either appends or reads. Data is fully replicated for fault tolerance.", tags: ["shared-log", "flash", "sequencer"], seeAlso: ["zookeeper", "ramcloud"] },
  { id: "tigerbeetle", name: "TigerBeetle (VSR in production)", cat: "uvrr",
    authors: "TigerBeetle", venue: "docs.tigerbeetle.com/concepts/safety",
    url: "https://docs.tigerbeetle.com/concepts/safety",
    abstract: "TigerBeetle implements pioneering Viewstamped Replication for correct automatic failover; consensus is engaged only during failover; uses Flexible Quorums and Protocol-Aware Recovery; assumes disks will fail and repairs replicas proactively; multi-cloud deployment across three providers.", tags: ["VSR-in-production", "fault-models", "jepsen"], seeAlso: ["vrr2012", "par", "fqi2016", "uvrrpaper"] },
  { id: "uvrrpaper", name: "Diskless VRR with Unbounded Crash-Stop Reincarnation", cat: "uvrr",
    authors: "Simon Massey", venue: "this repo, 2026 (paper.pdf)",
    url: "https://github.com/lua-lunet/uvrr-core",
    abstract: "uVRR: a protocol design for embedding strong consistency with volatile normal-path replication in small metadata clusters; crash-stop members reincarnate through fresh identities via a leader-driven weighted reconfiguration schedule; Lean 4 proof of per-slot agreement.", tags: ["crash-stop-reincarnation", "weighted-reconfiguration", "lean4", "sans-io"], seeAlso: ["vrr2012", "turner", "curp", "tigerbeetle", "diskless"] },
  { id: "blogVW", name: "Paxos Voting Weights (blog)", cat: "selfBlog",
    authors: "simbo1905", venue: "2017, simbo1905.wordpress.com",
    url: "https://simbo1905.wordpress.com/2017/03/16/paxos-voting-weights/",
    abstract: "Walks through Turner's hot-swap example using voting weights: double all weights, add the new node at 1, then halve; unit steps keep consecutive majorities overlapping. Zero-weight acceptors are learners/standbys.", tags: ["voting-weights", "worked-example"], seeAlso: ["turner", "blogUPaxos", "uvrrpaper"] },
  { id: "blogUPaxos", name: "UPaxos: Unbounded Paxos Reconfigurations (blog)", cat: "selfBlog",
    authors: "simbo1905", venue: "2016, simbo1905.wordpress.com",
    url: "https://simbo1905.wordpress.com/2016/12/16/upaxos-unbounded-paxos-reconfigurations/",
    abstract: "Explains Turner's UPaxos: era-indexed configurations, consecutive-configuration overlap QeI ⌢ Qe+1II, and the leader's casting vote enabling stall-free reconfiguration even when messages are lost.", tags: ["era-indexing", "casting-vote"], seeAlso: ["turner", "blogFrown", "uvrrpaper"] },
  { id: "blogFrown", name: "One More Frown Please (blog)", cat: "selfBlog",
    authors: "simbo1905", venue: "2020, simbo1905.wordpress.com",
    url: "https://simbo1905.wordpress.com/2020/05/23/one-more-frown-please-upaxos-quorum-overlaps/",
    abstract: "The frown operator and the exact quorum-overlap chain QIIe ⌢ QIe ⌢ QIIe+1 ⌢ QIe+1 required by UPaxos safety.", tags: ["overlap-chain", "frown-operator"], seeAlso: ["turner", "blogUPaxos"] },
  { id: "blogNetdisk", name: "The Network Is Faster Than the Disk (blog)", cat: "selfBlog",
    authors: "simbo1905", venue: "2024, simbo1905.wordpress.com",
    url: "https://simbo1905.wordpress.com/2024/04/12/the-network-is-faster-than-the-disk/",
    abstract: "Contrary to popular belief, the local disk may not always be faster than the network: measured fsync latencies (3ms for 256kB) vs sub-millisecond cross-AZ pings suggest VRR's diskless normal path is the right default.", tags: ["latency-economics", "fsync", "position"], seeAlso: ["vrr2012", "caseforramcloud", "blogUVRR"] },
  { id: "blogUVRR", name: "Unbounded Viewstamped Replication Revisited? (blog)", cat: "selfBlog",
    authors: "simbo1905", venue: "2026, simbo1905.wordpress.com",
    url: "https://simbo1905.wordpress.com/2026/08/12/viewstamped-replication-revisited/",
    abstract: "The motivation post: why has nobody open-sourced strong consistency with single-digit-millisecond primary failover and non-stop reconfiguration on VRR? TigerBeetle took the VRR high road but does not support dynamic cluster size.", tags: ["motivation", "research-gap"], seeAlso: ["vrr2012", "tigerbeetle", "blogNetdisk", "uvrrpaper"] }
];

// edges: [source, target, note] — source cites/targets/extends
const EDGES = [
  ["vrr2012", "vr1988", "revisits"],
  ["raft2014", "vr1988", "cites [27] Oki & Liskov"],
  ["raft2014", "vrr2012", "cites [20] Liskov & Cowling"],
  ["raft2014", "pms2001", "compares with Paxos"],
  ["ongarodiss", "raft2014", "dissertation extends"],
  ["logcabin", "raft2014", "built on Raft"],
  ["epaxosrev", "pms2001", "benchmarks Multi-Paxos"],
  ["curp", "ramcloud", "implemented in RAMCloud"],
  ["diskpaxos", "pms2001", "Paxos lineage"],
  ["verticalpaxos", "pms2001", "Paxos variant"],
  ["disc2017", "verticalpaxos", "journal version"],
  ["reconfigsm", "verticalpaxos", "tutorial lineage"],
  ["fqi2016", "pms2001", "relaxes Paxos quorums"],
  ["turner", "pms2001", "cites part-time parliament / PMS"],
  ["turner", "verticalpaxos", "cites Vertical Paxos"],
  ["turner", "fqi2016", "discovered independently (Turner's own words)"],
  ["diskless", "vrr2012", "studies VR recovery amnesia"],
  ["par", "raft2014", "recovery analysis of Raft"],
  ["par", "zookeeper", "recovery analysis of Zab"],
  ["homa2018", "ramcloud", "motivation: µs RPC"],
  ["homalinux", "homa2018", "kernel implementation"],
  ["replacetcp", "homalinux", "position paper on Homa/Linux"],
  ["omatalk", "replacetcp", "extends the case, AI clusters"],
  ["caseforramcloud", "ramcloud", "position paper"],
  ["tigerbeetle", "vrr2012", "implements VSR"],
  ["tigerbeetle", "par", "uses Protocol-Aware Recovery"],
  ["tigerbeetle", "fqi2016", "uses Flexible Quorums"],
  ["blogVW", "turner", "explains Turner's weight rules"],
  ["blogUPaxos", "turner", "explains UPaxos"],
  ["blogFrown", "turner", "formalises overlap chain"],
  ["blogNetdisk", "vrr2012", "motivates diskless path"],
  ["blogUVRR", "vrr2012", "motivation"],
  ["blogUVRR", "tigerbeetle", "the one VRR production team"],
  ["uvrrpaper", "vrr2012", "cites"],
  ["uvrrpaper", "turner", "cites"],
  ["uvrrpaper", "diskless", "cites"],
  ["uvrrpaper", "par", "cites"],
  ["uvrrpaper", "allfs", "cites"],
  ["uvrrpaper", "optfs", "cites"],
  ["uvrrpaper", "lampson", "cites"],
  ["uvrrpaper", "zookeeper", "cites"],
  ["uvrrpaper", "corfu", "cites"],
  ["uvrrpaper", "blogVW", "cites (candidate for removal)"],
  ["uvrrpaper", "blogNetdisk", "cites (candidate for removal)"],
  ["uvrrpaper", "blogUVRR", "cites (candidate for removal)"]
];
